services:
  - type: web
    name: stardom-web
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: stardom
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
